debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}
  register-with-eureka: true
    fetchRegistry: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
